neovim-bin = "zincvim"

[font]
normal = ["Maple Mono SC NF"]
size = 16

[font.features]
"Maple Mono SC NF" = [
  "+cv01",
  "+cv02",
  "+cv03",
  "+cv04",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
]
