[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red) "

[cmd_duration]
min_time = 10_000                    # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "bold dimmed white"

[hostname]
ssh_only = false
format = "<[$hostname]($style)> "
trim_at = "-"
style = "bold dimmed red"
disabled = false


[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[package]
disabled = true

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = true

[username]
style_user = "bold dimmed blue"
show_always = true
